### ISSUE TITLE
Editing a screenshot keeps the original

### ISSUE THREAD

**Issue by XeZrunner** [PixelExperience/external_asus_stitchimage#1]
How to reproduce:
1. Take a screenshot.
2. Tap 'Edit'.
3. Save the edited screenshot.

Expected result:
The original picture would be deleted or overriden with the edited one.
I would expect this behavior considering the original Pixels and previous versions of PE.

Result:
Both original and edited screenshots stay in the gallery.

Since this is only a part of Pixel Experience Plus, a toggle for "Keep original screenshots" could also be an option.
This being an external application, I'm not sure if modifications are possible.

**Comment by jhenrique09** [comment]
Implemented
